version: "3.8"

services:
  api-tests:
    build: .
    container_name: ntt-challenge-api
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app/api
    env_file:
      - ./api/.env
    environment:
      - NODE_ENV=development
    mem_limit: 4g
    memswap_limit: 4g
    command: ["yarn", "api:test"]

  web-tests:
    build: .
    container_name: ntt-challenge-web
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app/web
    env_file:
      - ./web/.env
    environment:
      - NODE_ENV=development
    mem_limit: 4g
    memswap_limit: 4g
    command: ["yarn", "web:test"]
